-- ==========================================================================
-- Park Day Companion — תוכן: חלק 2 מתוך 2
-- ==========================================================================
--
-- 99 מתקנים. להדביק ל-Supabase SQL Editor ולהריץ.
-- ⚠️ להריץ את החלקים לפי הסדר: 1, ואז 2.
--
-- נוצר על ידי scripts/build-content-seed.py מתוך src/data/experiences.json.
-- אין לערוך ביד — לעדכן את הייצוא ולהריץ את הסקריפט מחדש.
--
-- INSERT אחד מרובה-שורות. רשימת העמודות נכתבת פעם אחת.
--
-- on conflict do update מרענן את **כל** 37 העמודות מ-excluded,
-- גם כשהערך החדש NULL. עמודה שחסרה שם הייתה משאירה ערך ישן לנצח: מתקן
-- שדירוג העוצמה שלו הוסר בייצוא חדש היה נשאר עם הדירוג הישן, ושום דבר לא
-- היה נראה שבור — בתא יש ערך, הוא פשוט שגוי. לכן ה-SET נגזר מאותה רשימת
-- עמודות ולא נכתב שוב.
--
-- אפשר להריץ שוב בבטחה, כמה פעמים שרוצים.
--
-- ==========================================================================

BEGIN;

set local search_path = public, extensions;

insert into experience
  (id, key, park_id, land_id, kind, type, category, status, status_note, admission, reservation, included_with_admission, subtype, name, name_i18n, aliases_i18n, intensity, opened_year, duration_minutes, height_requirement_cm, max_height_requirement_cm, gets_wet, environment, air_conditioned, wheelchair, motion_sickness_warning, is_motion_simulator, uses_large_screens_or_3d, big_drops, spinning, skip_line_system, sens_enclosed_dark, sens_heights, sens_loud_sudden, sens_strobe, max_speed_kmh, inversions, last_verified)
values
('universal-epic-universe-dark-universe-character-meet-greet', 'Universal Epic Universe|Entertainment|Dark Universe Character Meet & Greet', 'epic', 'epic-dark-universe', 'entertainment', 'meet_greet', 'meet_greet', 'open', null, 'Valid admission to Universal Epic Universe (1-Day Epic Universe ticket or eligible multi-day/pass product that includes Epic Universe).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Character show', 'Dark Universe Character Meet & Greet', '{"he": "דארק יוניברס קרקטר מיט אנד גריט"}'::jsonb, '{"he": []}'::jsonb, 1, 2025, null, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'false', 'false', null, null, '2026-08-24'),
('universal-epic-universe-darkmoor-monster-makeup-experience', 'Universal Epic Universe|Attraction|Darkmoor Monster Makeup Experience', 'epic', 'epic-dark-universe', 'attraction', 'meet_greet', 'meet_greet', 'open', null, 'Valid admission to Universal Epic Universe (1-Day Epic Universe ticket or eligible multi-day/pass product that includes Epic Universe).', 'Separate paid experience reservation/ticket required in addition to valid Epic Universe admission. Check current official pricing/availability.', 'No – separate paid experience in addition to park admission', 'Makeover experience', 'Darkmoor Monster Makeup Experience', '{"he": "דארקמור מונסטר מייק-אפ אקספיריינס"}'::jsonb, '{"he": []}'::jsonb, 1, 2025, null, 0, null, 'none', 'outdoor', 'false', 'remain_in_wheelchair', 'false', 'na', 'na', 'na', 'na', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-epic-universe-monsters-unchained-the-frankenstein-experiment', 'Universal Epic Universe|Attraction|Monsters Unchained: The Frankenstein Experiment', 'epic', 'epic-dark-universe', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Epic Universe (1-Day Epic Universe ticket or eligible multi-day/pass product that includes Epic Universe).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Dark ride', 'Monsters Unchained: The Frankenstein Experiment', '{"he": "מונסטרס אנצ''יינד: דה פרנקנשטיין אקספרימנט"}'::jsonb, '{"he": []}'::jsonb, 3, 2025, 5, 122, null, 'none', 'indoor', 'true', 'transfer_to_ride_vehicle', 'false', 'false', 'true', 'false', 'true', null, 'true', 'false', 'true', 'true', null, null, '2026-08-24'),
('universal-epic-universe-dragon-racer-s-rally', 'Universal Epic Universe|Attraction|Dragon Racer''s Rally', 'epic', 'epic-how-to-train-your-dragon-isle-of-berk', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Epic Universe (1-Day Epic Universe ticket or eligible multi-day/pass product that includes Epic Universe).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Spinner', 'Dragon Racer''s Rally', '{"he": "דראגון רייסרס ראלי"}'::jsonb, '{"he": []}'::jsonb, 3, 2025, 3, 122, null, 'none', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'true', 'false', 'false', 'false', 'true', null, 'false', 'true', 'true', 'false', null, null, '2026-08-24'),
('universal-epic-universe-fyre-drill', 'Universal Epic Universe|Attraction|Fyre Drill', 'epic', 'epic-how-to-train-your-dragon-isle-of-berk', 'attraction', 'attraction', 'water_ride', 'open', null, 'Valid admission to Universal Epic Universe (1-Day Epic Universe ticket or eligible multi-day/pass product that includes Epic Universe).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Log flume', 'Fyre Drill', '{"he": "פייר דריל"}'::jsonb, '{"he": []}'::jsonb, 1, 2025, 5, 0, null, 'may_get_wet', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'false', 'false', 'false', 'false', 'false', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-epic-universe-hiccup-s-wing-gliders', 'Universal Epic Universe|Attraction|Hiccup''s Wing Gliders', 'epic', 'epic-how-to-train-your-dragon-isle-of-berk', 'attraction', 'attraction', 'coaster', 'open', null, 'Valid admission to Universal Epic Universe (1-Day Epic Universe ticket or eligible multi-day/pass product that includes Epic Universe).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Launch coaster', 'Hiccup''s Wing Gliders', '{"he": "היקאפס ווינג גליידרס"}'::jsonb, '{"he": []}'::jsonb, 3, 2025, 2, 102, null, 'none', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'true', 'false', 'false', 'true', 'false', null, 'false', 'true', 'false', 'false', 72, 0, '2026-08-24'),
('universal-epic-universe-meet-toothless-and-friends', 'Universal Epic Universe|Entertainment|Meet Toothless and Friends', 'epic', 'epic-how-to-train-your-dragon-isle-of-berk', 'entertainment', 'meet_greet', 'meet_greet', 'open', null, 'Valid admission to Universal Epic Universe (1-Day Epic Universe ticket or eligible multi-day/pass product that includes Epic Universe).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Character show', 'Meet Toothless and Friends', '{"he": "מיט טות''לס אנד פרנדס"}'::jsonb, '{"he": []}'::jsonb, 1, 2025, null, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'false', 'false', null, null, '2026-08-24'),
('universal-epic-universe-the-untrainable-dragon', 'Universal Epic Universe|Entertainment|The Untrainable Dragon', 'epic', 'epic-how-to-train-your-dragon-isle-of-berk', 'entertainment', 'show', 'show', 'open', null, 'Valid admission to Universal Epic Universe (1-Day Epic Universe ticket or eligible multi-day/pass product that includes Epic Universe).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Stage show', 'The Untrainable Dragon', '{"he": "דה אנטריינבל דראגון"}'::jsonb, '{"he": []}'::jsonb, 1, 2025, 20, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'true', 'na', 'true', 'true', null, null, '2026-08-24'),
('universal-epic-universe-viking-training-camp', 'Universal Epic Universe|Attraction|Viking Training Camp', 'epic', 'epic-how-to-train-your-dragon-isle-of-berk', 'attraction', 'attraction', 'playground', 'open', null, 'Valid admission to Universal Epic Universe (1-Day Epic Universe ticket or eligible multi-day/pass product that includes Epic Universe).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Play area', 'Viking Training Camp', '{"he": "וייקינג טריינינג קאמפ"}'::jsonb, '{"he": []}'::jsonb, 1, 2025, null, 0, null, 'none', 'outdoor', 'false', 'remain_in_wheelchair', 'false', 'na', 'na', 'na', 'na', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-epic-universe-mario-kart-bowser-s-challenge', 'Universal Epic Universe|Attraction|Mario Kart: Bowser''s Challenge', 'epic', 'epic-super-nintendo-world', 'attraction', 'attraction', '360_film', 'open', null, 'Valid admission to Universal Epic Universe (1-Day Epic Universe ticket or eligible multi-day/pass product that includes Epic Universe).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', '3D / 4D ride', 'Mario Kart: Bowser''s Challenge', '{"he": "מריו קארט: באוזרס צ''אלנג''"}'::jsonb, '{"he": ["מריו קארט"]}'::jsonb, 2, 2025, 5, 102, null, 'none', 'indoor', 'true', 'transfer_to_ride_vehicle', 'true', 'true', 'true', 'false', 'true', 'express', 'true', 'false', 'true', 'true', null, null, '2026-08-24'),
('universal-epic-universe-meet-mario-luigi-princess-peach-and-toad', 'Universal Epic Universe|Entertainment|Meet Mario, Luigi, Princess Peach and Toad', 'epic', 'epic-super-nintendo-world', 'entertainment', 'meet_greet', 'meet_greet', 'open', null, 'Valid admission to Universal Epic Universe (1-Day Epic Universe ticket or eligible multi-day/pass product that includes Epic Universe).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Character show', 'Meet Mario, Luigi, Princess Peach and Toad', '{"he": "מיט מריו, לואיג''י, פרינסס פיץ'' וטואד"}'::jsonb, '{"he": []}'::jsonb, 1, 2025, null, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'false', 'false', null, null, '2026-08-24'),
('universal-epic-universe-yoshi-s-adventure', 'Universal Epic Universe|Attraction|Yoshi''s Adventure', 'epic', 'epic-super-nintendo-world', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Epic Universe (1-Day Epic Universe ticket or eligible multi-day/pass product that includes Epic Universe).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Dark ride', 'Yoshi''s Adventure', '{"he": "יושיז אדוונצ''ר"}'::jsonb, '{"he": []}'::jsonb, 1, 2025, 5, 86, null, 'none', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'false', 'false', 'false', 'false', 'false', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-epic-universe-meet-donkey-kong', 'Universal Epic Universe|Entertainment|Meet Donkey Kong', 'epic', 'epic-super-nintendo-world-donkey-kong-country', 'entertainment', 'meet_greet', 'meet_greet', 'open', null, 'Valid admission to Universal Epic Universe (1-Day Epic Universe ticket or eligible multi-day/pass product that includes Epic Universe).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Character show', 'Meet Donkey Kong', '{"he": "מיט דונקי קונג"}'::jsonb, '{"he": []}'::jsonb, 1, 2025, null, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'false', 'false', null, null, '2026-08-24'),
('universal-epic-universe-mine-cart-madness', 'Universal Epic Universe|Attraction|Mine-Cart Madness', 'epic', 'epic-super-nintendo-world-donkey-kong-country', 'attraction', 'attraction', 'coaster', 'open', null, 'Valid admission to Universal Epic Universe (1-Day Epic Universe ticket or eligible multi-day/pass product that includes Epic Universe).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Roller coaster', 'Mine-Cart Madness', '{"he": "מיין-קארט מדנס"}'::jsonb, '{"he": []}'::jsonb, 3, 2025, 3, 102, null, 'none', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'true', 'false', 'false', 'true', 'false', null, 'false', 'true', 'true', 'false', null, null, '2026-08-24'),
('universal-epic-universe-harry-potter-and-the-battle-at-the-ministry', 'Universal Epic Universe|Attraction|Harry Potter and the Battle at the Ministry', 'epic', 'epic-the-wizarding-world-of-harry-potter-ministry-of-magic', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Epic Universe (1-Day Epic Universe ticket or eligible multi-day/pass product that includes Epic Universe).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Dark ride', 'Harry Potter and the Battle at the Ministry', '{"he": "הארי פוטר אנד דה באטל אט דה מיניסטרי"}'::jsonb, '{"he": ["מיניסטרי"]}'::jsonb, 3, 2025, 7, 102, null, 'none', 'indoor', 'true', 'transfer_to_ride_vehicle', 'true', 'true', 'true', 'false', 'true', 'express', 'true', 'false', 'true', 'true', null, null, '2026-08-24'),
('universal-epic-universe-le-cirque-arcanus', 'Universal Epic Universe|Entertainment|Le Cirque Arcanus', 'epic', 'epic-the-wizarding-world-of-harry-potter-ministry-of-magic', 'entertainment', 'show', 'show', 'open', null, 'Valid admission to Universal Epic Universe (1-Day Epic Universe ticket or eligible multi-day/pass product that includes Epic Universe).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Stage show', 'Le Cirque Arcanus', '{"he": "לה סירק ארקנוס"}'::jsonb, '{"he": []}'::jsonb, 1, 2025, 20, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'true', 'na', 'na', null, 'true', 'na', 'true', 'true', null, null, '2026-08-24'),
('universal-islands-of-adventure-frog-choir', 'Universal Islands of Adventure|Entertainment|Frog Choir', 'ioa', 'ioa-hogsmeade', 'entertainment', 'show', 'show', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Live music', 'Frog Choir', '{"he": "פרוג קווייר"}'::jsonb, '{"he": []}'::jsonb, 1, 2010, 10, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'false', 'false', null, null, '2026-08-24'),
('universal-islands-of-adventure-ollivanders-hogsmeade', 'Universal Islands of Adventure|Attraction|Ollivanders – Hogsmeade', 'ioa', 'ioa-hogsmeade', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Interactive dark ride', 'Ollivanders – Hogsmeade', '{"he": "אוליבנדרס – הוגסמיד"}'::jsonb, '{"he": []}'::jsonb, 1, 2010, 7, 0, null, 'none', 'indoor', 'true', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'true', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-islands-of-adventure-triwizard-spirit-rally', 'Universal Islands of Adventure|Entertainment|Triwizard Spirit Rally', 'ioa', 'ioa-hogsmeade', 'entertainment', 'show', 'show', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Stage show', 'Triwizard Spirit Rally', '{"he": "טריוויזרד ספיריט ראלי"}'::jsonb, '{"he": []}'::jsonb, 1, 2010, 10, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'true', 'false', null, null, '2026-08-24'),
('universal-islands-of-adventure-camp-jurassic', 'Universal Islands of Adventure|Attraction|Camp Jurassic', 'ioa', 'ioa-jurassic-park', 'attraction', 'attraction', 'playground', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Play area', 'Camp Jurassic', '{"he": "קאמפ ג''וראסיק"}'::jsonb, '{"he": []}'::jsonb, 1, 1999, null, 0, null, 'none', 'outdoor', 'false', 'remain_in_wheelchair', 'false', 'na', 'na', 'na', 'na', null, 'true', 'false', 'false', 'false', null, null, '2026-08-25'),
('universal-islands-of-adventure-jurassic-park-discovery-center', 'Universal Islands of Adventure|Attraction|Jurassic Park Discovery Center', 'ioa', 'ioa-jurassic-park', 'attraction', 'walkthrough', 'walkthrough', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Walk-through', 'Jurassic Park Discovery Center', '{"he": "ג''וראסיק פארק דיסקברי סנטר"}'::jsonb, '{"he": []}'::jsonb, 1, 1999, null, 0, null, 'none', 'outdoor', 'false', 'remain_in_wheelchair', 'false', 'na', 'na', 'na', 'na', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-islands-of-adventure-jurassic-park-river-adventure', 'Universal Islands of Adventure|Attraction|Jurassic Park River Adventure', 'ioa', 'ioa-jurassic-park', 'attraction', 'attraction', 'dark_ride', 'closed', 'Temporarily unavailable Jan 5–Nov 19, 2026 (official Universal closure schedule).', 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Drop ride', 'Jurassic Park River Adventure', '{"he": "ג''וראסיק פארק ריבר אדוונצ''ר"}'::jsonb, '{"he": []}'::jsonb, 3, 1999, 7, 107, null, 'may_get_soaked', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'false', 'false', 'false', 'true', 'false', 'express', 'true', 'true', 'true', 'true', null, null, '2026-08-24'),
('universal-islands-of-adventure-jurassic-world-velocicoaster', 'Universal Islands of Adventure|Attraction|Jurassic World VelociCoaster', 'ioa', 'ioa-jurassic-park', 'attraction', 'attraction', 'coaster', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Launch coaster', 'Jurassic World VelociCoaster', '{"he": "ג''וראסיק וורלד ולוסיקוסטר"}'::jsonb, '{"he": ["ולוסיקוסטר"]}'::jsonb, 4, 2021, 2, 130, null, 'none', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'true', 'false', 'false', 'true', 'false', null, 'false', 'true', 'true', 'false', 113, 4, '2026-08-24'),
('universal-islands-of-adventure-pteranodon-flyers', 'Universal Islands of Adventure|Attraction|Pteranodon Flyers', 'ioa', 'ioa-jurassic-park', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Dark ride', 'Pteranodon Flyers', '{"he": "פטרנודון פליירס"}'::jsonb, '{"he": []}'::jsonb, 1, 1999, 2, 91, null, 'none', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'false', 'false', 'false', 'false', 'false', null, 'false', 'true', 'false', 'false', null, null, '2026-08-24'),
('universal-islands-of-adventure-raptor-encounter', 'Universal Islands of Adventure|Attraction|Raptor Encounter', 'ioa', 'ioa-jurassic-park', 'attraction', 'meet_greet', 'meet_greet', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Character meet', 'Raptor Encounter', '{"he": "ראפטור אנקאונטר"}'::jsonb, '{"he": []}'::jsonb, 2, 2015, null, 0, null, 'none', 'outdoor', 'false', 'remain_in_wheelchair', 'false', 'na', 'na', 'na', 'na', null, 'false', 'false', 'true', 'false', null, null, '2026-08-25'),
('universal-islands-of-adventure-doctor-doom-s-fearfall', 'Universal Islands of Adventure|Attraction|Doctor Doom''s Fearfall', 'ioa', 'ioa-marvel-super-hero-island', 'attraction', 'attraction', 'coaster', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Launch coaster', 'Doctor Doom''s Fearfall', '{"he": "דוקטור דומס פירפול"}'::jsonb, '{"he": []}'::jsonb, 4, 1999, 1, 132, null, 'none', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'true', 'false', 'false', 'true', 'false', 'express', 'false', 'true', 'true', 'true', 64, null, '2026-08-24'),
('universal-islands-of-adventure-meet-the-marvel-super-heroes', 'Universal Islands of Adventure|Entertainment|Meet the Marvel Super Heroes', 'ioa', 'ioa-marvel-super-hero-island', 'entertainment', 'meet_greet', 'meet_greet', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Character show', 'Meet the Marvel Super Heroes', '{"he": "מיט דה מארוול סופר הירוז"}'::jsonb, '{"he": []}'::jsonb, 1, 1999, null, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'false', 'false', null, null, '2026-08-24'),
('universal-islands-of-adventure-storm-force-accelatron', 'Universal Islands of Adventure|Attraction|Storm Force Accelatron', 'ioa', 'ioa-marvel-super-hero-island', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Spinner', 'Storm Force Accelatron', '{"he": "סטורם פורס אקסלטרון"}'::jsonb, '{"he": []}'::jsonb, 1, 2000, 4, 0, null, 'none', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'true', 'false', 'false', 'false', 'true', 'express', 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-islands-of-adventure-the-amazing-adventures-of-spider-man', 'Universal Islands of Adventure|Attraction|The Amazing Adventures of Spider-Man', 'ioa', 'ioa-marvel-super-hero-island', 'attraction', 'attraction', '360_film', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', '3D / 4D ride', 'The Amazing Adventures of Spider-Man', '{"he": "דה אמייזינג אדוונצ''רס אוף ספיידרמן"}'::jsonb, '{"he": []}'::jsonb, 2, 1999, 5, 102, null, 'none', 'indoor', 'true', 'transfer_to_ride_vehicle', 'true', 'true', 'true', 'false', 'true', 'express', 'true', 'false', 'true', 'true', null, null, '2026-08-24'),
('universal-islands-of-adventure-the-incredible-hulk-coaster', 'Universal Islands of Adventure|Attraction|The Incredible Hulk Coaster', 'ioa', 'ioa-marvel-super-hero-island', 'attraction', 'attraction', 'coaster', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Roller coaster', 'The Incredible Hulk Coaster', '{"he": "דה אינקרדיבל האלק קוסטר"}'::jsonb, '{"he": []}'::jsonb, 4, 1999, 2, 137, null, 'none', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'true', 'false', 'false', 'true', 'false', 'express', 'false', 'true', 'true', 'true', 108, 7, '2026-08-24'),
('universal-islands-of-adventure-caro-seuss-el', 'Universal Islands of Adventure|Attraction|Caro-Seuss-el', 'ioa', 'ioa-seuss-landing', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Carousel', 'Caro-Seuss-el', '{"he": "קארו-סוס-אל"}'::jsonb, '{"he": []}'::jsonb, 1, 1999, 2, 0, null, 'none', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'false', 'false', 'false', 'false', 'true', 'express', 'false', 'false', 'false', 'false', null, null, '2026-08-25'),
('universal-islands-of-adventure-dr-seuss-character-zone', 'Universal Islands of Adventure|Entertainment|Dr. Seuss Character Zone', 'ioa', 'ioa-seuss-landing', 'entertainment', 'meet_greet', 'meet_greet', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Character show', 'Dr. Seuss Character Zone', '{"he": "דוקטור סוס קרקטר זון"}'::jsonb, '{"he": []}'::jsonb, 1, 1999, null, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'false', 'false', null, null, '2026-08-24'),
('universal-islands-of-adventure-if-i-ran-the-zoo', 'Universal Islands of Adventure|Attraction|If I Ran The Zoo', 'ioa', 'ioa-seuss-landing', 'attraction', 'attraction', 'playground', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Play area', 'If I Ran The Zoo', '{"he": "איף איי ראן דה זו"}'::jsonb, '{"he": []}'::jsonb, 1, 1999, null, 0, null, 'none', 'outdoor', 'false', 'remain_in_wheelchair', 'false', 'na', 'na', 'na', 'na', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-islands-of-adventure-oh-the-stories-you-ll-hear', 'Universal Islands of Adventure|Entertainment|Oh! The Stories You''ll Hear!', 'ioa', 'ioa-seuss-landing', 'entertainment', 'show', 'show', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Stage show', 'Oh! The Stories You''ll Hear!', '{"he": "או! דה סטוריז יול היר"}'::jsonb, '{"he": []}'::jsonb, 1, 1999, 20, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'false', 'false', null, null, '2026-08-24'),
('universal-islands-of-adventure-one-fish-two-fish-red-fish-blue-fish', 'Universal Islands of Adventure|Attraction|One Fish, Two Fish, Red Fish, Blue Fish', 'ioa', 'ioa-seuss-landing', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Spinner', 'One Fish, Two Fish, Red Fish, Blue Fish', '{"he": "וואן פיש, טו פיש, רד פיש, בלו פיש"}'::jsonb, '{"he": []}'::jsonb, 1, 1999, 4, 0, null, 'may_get_wet', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'false', 'false', 'false', 'false', 'true', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-islands-of-adventure-the-cat-in-the-hat', 'Universal Islands of Adventure|Attraction|The Cat in the Hat', 'ioa', 'ioa-seuss-landing', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Dark ride', 'The Cat in the Hat', '{"he": "דה קאט אין דה האט"}'::jsonb, '{"he": []}'::jsonb, 1, 1999, 4, 91, null, 'none', 'indoor', 'true', 'transfer_to_ride_vehicle', 'false', 'false', 'false', 'false', 'true', 'express', 'true', 'false', 'true', 'true', null, null, '2026-08-24'),
('universal-islands-of-adventure-the-high-in-the-sky-seuss-trolley-train-ride', 'Universal Islands of Adventure|Attraction|The High in the Sky Seuss Trolley Train Ride!', 'ioa', 'ioa-seuss-landing', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Dark ride', 'The High in the Sky Seuss Trolley Train Ride!', '{"he": "דה היי אין דה סקיי סוס טרולי טריין"}'::jsonb, '{"he": []}'::jsonb, 1, 2006, 6, 91, null, 'none', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'false', 'false', 'false', 'false', 'false', 'express', 'false', 'true', 'false', 'false', null, null, '2026-08-24'),
('universal-islands-of-adventure-skull-island-reign-of-kong', 'Universal Islands of Adventure|Attraction|Skull Island: Reign of Kong', 'ioa', 'ioa-skull-island', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Dark ride', 'Skull Island: Reign of Kong', '{"he": "סקאל איילנד: ריין אוף קונג"}'::jsonb, '{"he": []}'::jsonb, 2, 2016, 6, 91, null, 'none', 'indoor', 'true', 'transfer_to_ride_vehicle', 'true', 'true', 'true', 'false', 'false', 'express', 'true', 'false', 'true', 'true', null, null, '2026-08-24'),
('universal-islands-of-adventure-flight-of-the-hippogriff', 'Universal Islands of Adventure|Attraction|Flight of the Hippogriff', 'ioa', 'ioa-the-wizarding-world-of-harry-potter-hogsmeade', 'attraction', 'attraction', 'coaster', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Family coaster', 'Flight of the Hippogriff', '{"he": "פלייט אוף דה היפוגריף"}'::jsonb, '{"he": []}'::jsonb, 2, 2010, 1, 91, null, 'none', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'false', 'false', 'false', 'false', 'false', 'express', 'false', 'false', 'false', 'false', 47, 0, '2026-08-25'),
('universal-islands-of-adventure-hagrid-s-magical-creatures-motorbike-adventure', 'Universal Islands of Adventure|Attraction|Hagrid''s Magical Creatures Motorbike Adventure', 'ioa', 'ioa-the-wizarding-world-of-harry-potter-hogsmeade', 'attraction', 'attraction', 'coaster', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Launch coaster', 'Hagrid''s Magical Creatures Motorbike Adventure', '{"he": "האגרידס מג''יקל קריצ''רס מוטורבייק אדוונצ''ר"}'::jsonb, '{"he": ["האגריד"]}'::jsonb, 3, 2019, 3, 122, null, 'none', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'true', 'false', 'false', 'true', 'false', 'express', 'true', 'true', 'true', 'true', 80, 0, '2026-08-24'),
('universal-islands-of-adventure-harry-potter-and-the-forbidden-journey', 'Universal Islands of Adventure|Attraction|Harry Potter and the Forbidden Journey', 'ioa', 'ioa-the-wizarding-world-of-harry-potter-hogsmeade', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Dark ride', 'Harry Potter and the Forbidden Journey', '{"he": "הארי פוטר אנד דה פורבידן ג''ורני"}'::jsonb, '{"he": ["פורבידן ג''ורני"]}'::jsonb, 3, 2010, 4, 122, null, 'none', 'indoor', 'true', 'transfer_to_ride_vehicle', 'true', 'true', 'true', 'false', 'true', 'express', 'true', 'false', 'true', 'true', null, null, '2026-08-24'),
('universal-islands-of-adventure-hogwarts-express-hogsmeade-station', 'Universal Islands of Adventure|Attraction|Hogwarts Express – Hogsmeade Station', 'ioa', 'ioa-the-wizarding-world-of-harry-potter-hogsmeade', 'attraction', 'attraction', 'scenic_ride', 'open', null, 'Park-to-Park admission covering Universal Studios Florida + Universal Islands of Adventure, or an eligible Annual/Seasonal Pass, is REQUIRED. A one-park ticket is not sufficient.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Train', 'Hogwarts Express – Hogsmeade Station', '{"he": "הוגוורטס אקספרס – הוגסמיד"}'::jsonb, '{"he": []}'::jsonb, 1, 2014, 4, 0, null, 'none', 'indoor', 'true', 'remain_in_wheelchair', 'false', 'false', 'true', 'false', 'false', null, 'true', 'false', 'true', 'false', null, null, '2026-08-24'),
('universal-islands-of-adventure-classic-comic-strip-characters', 'Universal Islands of Adventure|Entertainment|Classic Comic Strip Characters', 'ioa', 'ioa-toon-lagoon', 'entertainment', 'meet_greet', 'meet_greet', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Character show', 'Classic Comic Strip Characters', '{"he": "קלאסיק קומיק סטריפ קרקטרס"}'::jsonb, '{"he": []}'::jsonb, 1, 1999, null, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'false', 'false', null, null, '2026-08-24'),
('universal-islands-of-adventure-dudley-do-right-s-ripsaw-falls', 'Universal Islands of Adventure|Attraction|Dudley Do-Right''s Ripsaw Falls', 'ioa', 'ioa-toon-lagoon', 'attraction', 'attraction', 'water_ride', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Log flume', 'Dudley Do-Right''s Ripsaw Falls', '{"he": "דאדלי דו-רייטס ריפסו פולס"}'::jsonb, '{"he": []}'::jsonb, 2, 1999, 7, 112, null, 'may_get_soaked', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'false', 'false', 'false', 'true', 'false', 'express', 'false', 'true', 'false', 'false', null, null, '2026-08-24'),
('universal-islands-of-adventure-me-ship-the-olive', 'Universal Islands of Adventure|Attraction|Me Ship, The Olive', 'ioa', 'ioa-toon-lagoon', 'attraction', 'attraction', 'playground', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Play area', 'Me Ship, The Olive', '{"he": "מי שיפ, דה אוליב"}'::jsonb, '{"he": []}'::jsonb, 1, 1999, null, 0, null, 'none', 'outdoor', 'false', 'remain_in_wheelchair', 'false', 'na', 'na', 'na', 'na', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-islands-of-adventure-popeye-bluto-s-bilge-rat-barges', 'Universal Islands of Adventure|Attraction|Popeye & Bluto''s Bilge-Rat Barges', 'ioa', 'ioa-toon-lagoon', 'attraction', 'attraction', 'water_ride', 'open', null, 'Valid admission to Universal Islands of Adventure (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'River rapids', 'Popeye & Bluto''s Bilge-Rat Barges', '{"he": "פופאי אנד בלוטוז בילג''-ראט בארג''ס"}'::jsonb, '{"he": []}'::jsonb, 2, 1999, 10, 107, null, 'may_get_soaked', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'false', 'false', 'false', 'false', 'true', 'express', 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-studios-florida-celestina-warbeck-and-the-banshees', 'Universal Studios Florida|Entertainment|Celestina Warbeck and the Banshees', 'us', 'us-diagon-alley', 'entertainment', 'show', 'show', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Live music', 'Celestina Warbeck and the Banshees', '{"he": "סלסטינה וורבק אנד דה באנשיז"}'::jsonb, '{"he": []}'::jsonb, 1, 2014, 12, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'true', 'false', null, null, '2026-08-24'),
('universal-studios-florida-ollivanders-diagon-alley', 'Universal Studios Florida|Attraction|Ollivanders – Diagon Alley', 'us', 'us-diagon-alley', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Interactive dark ride', 'Ollivanders – Diagon Alley', '{"he": "אוליבנדרס – דיאגון אלי"}'::jsonb, '{"he": []}'::jsonb, 1, 2014, 7, 0, null, 'none', 'indoor', 'true', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'true', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-studios-florida-the-tales-of-beedle-the-bard', 'Universal Studios Florida|Entertainment|The Tales of Beedle the Bard', 'us', 'us-diagon-alley', 'entertainment', 'show', 'show', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Stage show', 'The Tales of Beedle the Bard', '{"he": "דה טיילס אוף בידל דה בארד"}'::jsonb, '{"he": []}'::jsonb, 1, 2014, 10, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'true', 'false', null, null, '2026-08-24'),
('universal-studios-florida-dreamworks-imagination-celebration', 'Universal Studios Florida|Entertainment|DreamWorks Imagination Celebration', 'us', 'us-dreamworks-land', 'entertainment', 'show', 'show', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Stage show', 'DreamWorks Imagination Celebration', '{"he": "דרימוורקס אימג''יניישן סלבריישן"}'::jsonb, '{"he": []}'::jsonb, 1, 2024, 20, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'true', 'na', 'na', null, 'false', 'na', 'true', 'true', null, null, '2026-08-24'),
('universal-studios-florida-king-harold-s-swamp-symphony', 'Universal Studios Florida|Attraction|King Harold''s Swamp Symphony', 'us', 'us-dreamworks-land', 'attraction', 'attraction', 'playground', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Play area', 'King Harold''s Swamp Symphony', '{"he": "קינג הרולדס סוואמפ סימפוני"}'::jsonb, '{"he": []}'::jsonb, 1, 2024, null, 0, null, 'none', 'outdoor', 'false', 'remain_in_wheelchair', 'false', 'na', 'na', 'na', 'na', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-studios-florida-mama-luna-feline-fiesta', 'Universal Studios Florida|Attraction|Mama Luna Feline Fiesta', 'us', 'us-dreamworks-land', 'attraction', 'attraction', 'playground', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Play area', 'Mama Luna Feline Fiesta', '{"he": "מאמא לונה פיליין פיאסטה"}'::jsonb, '{"he": []}'::jsonb, 1, 2024, null, 0, null, 'none', 'outdoor', 'false', 'remain_in_wheelchair', 'false', 'na', 'na', 'na', 'na', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-studios-florida-po-live', 'Universal Studios Florida|Entertainment|Po Live!', 'us', 'us-dreamworks-land', 'entertainment', 'meet_greet', 'meet_greet', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Character show', 'Po Live!', '{"he": "פו לייב"}'::jsonb, '{"he": []}'::jsonb, 1, 2024, 10, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'true', 'na', 'na', null, 'false', 'na', 'true', 'false', null, null, '2026-08-24'),
('universal-studios-florida-po-s-kung-fu-training-camp', 'Universal Studios Florida|Attraction|Po''s Kung Fu Training Camp', 'us', 'us-dreamworks-land', 'attraction', 'attraction', 'playground', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Play area', 'Po''s Kung Fu Training Camp', '{"he": "פוז קונג פו טריינינג קאמפ"}'::jsonb, '{"he": []}'::jsonb, 1, 2024, null, 0, null, 'none', 'outdoor', 'false', 'remain_in_wheelchair', 'false', 'na', 'na', 'na', 'na', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-studios-florida-poppy-s-playground', 'Universal Studios Florida|Attraction|Poppy''s Playground', 'us', 'us-dreamworks-land', 'attraction', 'attraction', 'playground', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Play area', 'Poppy''s Playground', '{"he": "פופיז פלייגראונד"}'::jsonb, '{"he": []}'::jsonb, 1, 2024, null, 0, null, 'none', 'outdoor', 'false', 'remain_in_wheelchair', 'false', 'na', 'na', 'na', 'na', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-studios-florida-shrek-s-swamp-for-little-ogres', 'Universal Studios Florida|Attraction|Shrek''s Swamp for Little Ogres', 'us', 'us-dreamworks-land', 'attraction', 'attraction', 'playground', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Play area', 'Shrek''s Swamp for Little Ogres', '{"he": "שרקס סוואמפ פור ליטל אוגרס"}'::jsonb, '{"he": []}'::jsonb, 1, 2024, null, 0, null, 'none', 'outdoor', 'false', 'remain_in_wheelchair', 'false', 'na', 'na', 'na', 'na', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-studios-florida-trolls-trollercoaster', 'Universal Studios Florida|Attraction|Trolls Trollercoaster', 'us', 'us-dreamworks-land', 'attraction', 'attraction', 'coaster', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Family coaster', 'Trolls Trollercoaster', '{"he": "טרולס טרולרקוסטר"}'::jsonb, '{"he": []}'::jsonb, 2, 2024, 1, 91, null, 'none', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'false', 'false', 'false', 'false', 'false', 'express', 'false', 'false', 'false', 'false', 35, 0, '2026-08-24'),
('universal-studios-florida-animal-actors-on-location', 'Universal Studios Florida|Entertainment|Animal Actors On Location!', 'us', 'us-hollywood', 'entertainment', 'show', 'show', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Animal presentation', 'Animal Actors On Location!', '{"he": "אנימל אקטורס און לוקיישן"}'::jsonb, '{"he": []}'::jsonb, 1, 1990, 20, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'true', 'na', 'na', null, 'false', 'na', 'false', 'false', null, null, '2026-09-01'),
('universal-studios-florida-e-t-adventure', 'Universal Studios Florida|Attraction|E.T. Adventure', 'us', 'us-hollywood', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Dark ride', 'E.T. Adventure', '{"he": "אי.טי. אדוונצ''ר"}'::jsonb, '{"he": []}'::jsonb, 1, 1990, 5, 86, null, 'none', 'indoor', 'true', 'transfer_to_ride_vehicle', 'false', 'false', 'false', 'false', 'false', 'express', 'true', 'false', 'true', 'true', null, null, '2026-08-24'),
('universal-studios-florida-marilyn-and-the-diamond-bellas', 'Universal Studios Florida|Entertainment|Marilyn and the Diamond Bellas', 'us', 'us-hollywood', 'entertainment', 'show', 'show', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Stage show', 'Marilyn and the Diamond Bellas', '{"he": "מרילין אנד דה דיימונד בלאס"}'::jsonb, '{"he": []}'::jsonb, 1, 2016, 5, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'true', 'false', null, null, '2026-09-01'),
('universal-studios-florida-the-bourne-stuntacular', 'Universal Studios Florida|Entertainment|The Bourne Stuntacular', 'us', 'us-hollywood', 'entertainment', 'show', 'show', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Stunt show', 'The Bourne Stuntacular', '{"he": "דה בורן סטאנטקיולר"}'::jsonb, '{"he": []}'::jsonb, 1, 2020, 20, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'true', 'na', 'na', null, 'true', 'na', 'true', 'true', null, null, '2026-08-24'),
('universal-studios-florida-universal-orlando-s-horror-make-up-show', 'Universal Studios Florida|Entertainment|Universal Orlando''s Horror Make-Up Show', 'us', 'us-hollywood', 'entertainment', 'show', 'show', 'closed', 'Temporarily unavailable May 12, 2026–Winter 2026; reopening date not exact.', 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Stage show', 'Universal Orlando''s Horror Make-Up Show', '{"he": "יוניברסל אורלנדוז הורור מייק-אפ שואו"}'::jsonb, '{"he": []}'::jsonb, 1, 1990, 25, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'true', 'true', null, null, '2026-08-24'),
('universal-studios-florida-despicable-me-minion-mayhem', 'Universal Studios Florida|Attraction|Despicable Me Minion Mayhem', 'us', 'us-illumination-s-minion-land', 'attraction', 'attraction', 'simulator', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Motion simulator', 'Despicable Me Minion Mayhem', '{"he": "דספיקבל מי מיניון מייהם"}'::jsonb, '{"he": []}'::jsonb, 1, 2012, 8, 102, null, 'none', 'indoor', 'true', 'remain_in_wheelchair', 'true', 'true', 'true', 'false', 'false', 'express', 'true', 'false', 'true', 'true', null, null, '2026-08-24'),
('universal-studios-florida-illumination-theater', 'Universal Studios Florida|Entertainment|Illumination Theater', 'us', 'us-illumination-s-minion-land', 'entertainment', 'meet_greet', 'meet_greet', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Character show', 'Illumination Theater', '{"he": "אילומיניישן ת''יאטר"}'::jsonb, '{"he": []}'::jsonb, 1, 2023, null, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'true', 'false', null, null, '2026-08-24'),
('universal-studios-florida-illumination-s-villain-con-minion-blast', 'Universal Studios Florida|Attraction|Illumination''s Villain-Con Minion Blast', 'us', 'us-illumination-s-minion-land', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Interactive dark ride', 'Illumination''s Villain-Con Minion Blast', '{"he": "אילומיניישנ''ס וילן-קון מיניון בלאסט"}'::jsonb, '{"he": []}'::jsonb, 1, 2023, 5, 0, null, 'none', 'indoor', 'true', 'remain_in_wheelchair', 'false', 'false', 'true', 'false', 'false', 'express', 'true', 'false', 'true', 'true', null, null, '2026-08-24'),
('universal-studios-florida-vamos-bailalo', 'Universal Studios Florida|Entertainment|¡Vamos! – Báilalo', 'us', 'us-new-york', 'entertainment', 'show', 'show', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Stage show', '¡Vamos! – Báilalo', '{"he": "ואמוס – ביילאלו"}'::jsonb, '{"he": []}'::jsonb, 1, 2024, 10, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'true', 'false', null, null, '2026-08-24'),
('universal-studios-florida-race-through-new-york-starring-jimmy-fallon', 'Universal Studios Florida|Attraction|Race Through New York Starring Jimmy Fallon', 'us', 'us-new-york', 'attraction', 'attraction', 'simulator', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Motion simulator', 'Race Through New York Starring Jimmy Fallon', '{"he": "רייס ת''רו ניו יורק סטארינג ג''ימי פאלון"}'::jsonb, '{"he": []}'::jsonb, 2, 2017, 5, 102, null, 'none', 'indoor', 'true', 'transfer_to_ride_vehicle', 'true', 'true', 'true', 'false', 'false', 'express', 'true', 'false', 'true', 'true', null, null, '2026-08-24'),
('universal-studios-florida-revenge-of-the-mummy', 'Universal Studios Florida|Attraction|Revenge of the Mummy', 'us', 'us-new-york', 'attraction', 'attraction', 'coaster', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Indoor coaster', 'Revenge of the Mummy', '{"he": "רבנג'' אוף דה מאמי"}'::jsonb, '{"he": ["המומיה"]}'::jsonb, 3, 2004, 3, 122, null, 'none', 'indoor', 'true', 'transfer_to_ride_vehicle', 'true', 'false', 'false', 'true', 'false', 'express', 'true', 'false', 'true', 'true', 72, 0, '2026-08-24'),
('universal-studios-florida-the-blues-brothers-show', 'Universal Studios Florida|Entertainment|The Blues Brothers Show', 'us', 'us-new-york', 'entertainment', 'show', 'show', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Live music', 'The Blues Brothers Show', '{"he": "דה בלוז בראדרס שואו"}'::jsonb, '{"he": []}'::jsonb, 1, 1991, 20, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'true', 'false', null, null, '2026-08-24'),
('universal-studios-florida-transformers-the-ride-3d', 'Universal Studios Florida|Attraction|TRANSFORMERS: The Ride-3D', 'us', 'us-new-york-production-central', 'attraction', 'attraction', '360_film', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', '3D / 4D ride', 'TRANSFORMERS: The Ride-3D', '{"he": "טרנספורמרס: דה רייד 3D"}'::jsonb, '{"he": []}'::jsonb, 2, 2013, 5, 102, null, 'none', 'indoor', 'true', 'transfer_to_ride_vehicle', 'true', 'true', 'true', 'false', 'false', 'express', 'true', 'true', 'true', 'true', null, null, '2026-08-24'),
('universal-studios-florida-universal-mega-movie-parade', 'Universal Studios Florida|Entertainment|Universal Mega Movie Parade', 'us', 'us-park-wide-parade-route', 'entertainment', 'parade', 'show', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Parade', 'Universal Mega Movie Parade', '{"he": "יוניברסל מגה מובי פארייד"}'::jsonb, '{"he": []}'::jsonb, 1, 2024, 30, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'true', 'false', null, null, '2026-08-24'),
('universal-studios-florida-beat-builders', 'Universal Studios Florida|Entertainment|Beat Builders', 'us', 'us-san-francisco', 'entertainment', 'show', 'show', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Live music', 'Beat Builders', '{"he": "ביט בילדרס"}'::jsonb, '{"he": []}'::jsonb, 1, 2015, 15, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'true', 'false', null, null, '2026-09-01'),
('universal-studios-florida-fast-furious-supercharged', 'Universal Studios Florida|Attraction|Fast & Furious – Supercharged', 'us', 'us-san-francisco', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Dark ride', 'Fast & Furious – Supercharged', '{"he": "פאסט אנד פיוריוס: סופרצ''ארג''ד"}'::jsonb, '{"he": []}'::jsonb, 2, 2018, 5, 102, null, 'none', 'indoor', 'true', 'remain_in_wheelchair', 'true', 'true', 'true', 'false', 'false', 'express', 'true', 'false', 'true', 'true', null, null, '2026-08-24'),
('universal-studios-florida-kang-kodos-twirl-n-hurl', 'Universal Studios Florida|Attraction|Kang & Kodos'' Twirl ''n'' Hurl', 'us', 'us-springfield-u-s-a', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Spinner', 'Kang & Kodos'' Twirl ''n'' Hurl', '{"he": "קאנג אנד קודוס טווירל אנד הרל"}'::jsonb, '{"he": []}'::jsonb, 1, 2012, 2, 0, null, 'none', 'outdoor', 'false', 'transfer_to_ride_vehicle', 'false', 'false', 'false', 'false', 'true', null, 'false', 'false', 'true', 'false', null, null, '2026-08-24'),
('universal-studios-florida-the-simpsons-ride', 'Universal Studios Florida|Attraction|The Simpsons Ride', 'us', 'us-springfield-u-s-a', 'attraction', 'attraction', 'simulator', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Motion simulator', 'The Simpsons Ride', '{"he": "דה סימפסונס רייד"}'::jsonb, '{"he": []}'::jsonb, 1, 2008, 8, 102, null, 'none', 'indoor', 'true', 'transfer_to_ride_vehicle', 'true', 'true', 'true', 'false', 'false', 'express', 'true', 'true', 'true', 'true', null, null, '2026-08-24'),
('universal-studios-florida-harry-potter-and-the-escape-from-gringotts', 'Universal Studios Florida|Attraction|Harry Potter and the Escape from Gringotts', 'us', 'us-the-wizarding-world-of-harry-potter-diagon-alley', 'attraction', 'attraction', 'coaster', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Roller coaster', 'Harry Potter and the Escape from Gringotts', '{"he": "הארי פוטר אנד דה אסקייפ פרום גרינגוטס"}'::jsonb, '{"he": ["גרינגוטס"]}'::jsonb, 2, 2014, 5, 107, null, 'none', 'indoor', 'true', 'transfer_to_ride_vehicle', 'true', 'true', 'true', 'true', 'true', 'express', 'true', 'false', 'true', 'true', 34, 0, '2026-08-24'),
('universal-studios-florida-hogwarts-express-king-s-cross-station', 'Universal Studios Florida|Attraction|Hogwarts Express – King''s Cross Station', 'us', 'us-the-wizarding-world-of-harry-potter-diagon-alley', 'attraction', 'attraction', 'scenic_ride', 'open', null, 'Park-to-Park admission covering Universal Studios Florida + Universal Islands of Adventure, or an eligible Annual/Seasonal Pass, is REQUIRED. A one-park ticket is not sufficient.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Train', 'Hogwarts Express – King''s Cross Station', '{"he": "הוגוורטס אקספרס – קינגס קרוס"}'::jsonb, '{"he": []}'::jsonb, 1, 2014, 4, 0, null, 'none', 'indoor', 'true', 'remain_in_wheelchair', 'false', 'false', 'true', 'false', 'false', null, 'true', 'false', 'true', 'false', null, null, '2026-08-24'),
('universal-studios-florida-cinesational-a-symphonic-spectacular', 'Universal Studios Florida|Entertainment|CineSational: A Symphonic Spectacular', 'us', 'us-universal-studios-lagoon', 'entertainment', 'show', 'show', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Nighttime spectacular', 'CineSational: A Symphonic Spectacular', '{"he": "סינסיישנל: סימפוניק ספקטקיולר"}'::jsonb, '{"he": []}'::jsonb, 1, 2024, 22, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'true', 'na', 'na', null, 'false', 'na', 'true', 'true', null, null, '2026-08-24'),
('universal-studios-florida-men-in-black-alien-attack', 'Universal Studios Florida|Attraction|MEN IN BLACK Alien Attack', 'us', 'us-world-expo', 'attraction', 'attraction', 'dark_ride', 'open', null, 'Valid admission to Universal Studios Florida (1-Day park ticket or eligible multi-day/Annual/Seasonal Pass).', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Interactive dark ride', 'MEN IN BLACK Alien Attack', '{"he": "מן אין בלאק: אליין אטאק"}'::jsonb, '{"he": []}'::jsonb, 1, 2000, 5, 107, null, 'none', 'indoor', 'true', 'transfer_to_ride_vehicle', 'false', 'false', 'true', 'false', 'true', 'express', 'true', 'false', 'true', 'true', null, null, '2026-08-24'),
('universal-volcano-bay-ko-okiri-body-plunge', 'Universal Volcano Bay|Attraction|Ko''okiri Body Plunge', 'vb', 'vb-krakatau', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Body slide', 'Ko''okiri Body Plunge', '{"he": "קואוקירי בודי פלאנג''"}'::jsonb, '{"he": []}'::jsonb, 4, 2017, null, 122, null, 'may_get_soaked', 'outdoor', 'na', 'must_be_ambulatory', 'false', 'na', 'na', 'true', 'false', null, 'true', 'true', 'true', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-krakatau-aqua-coaster', 'Universal Volcano Bay|Attraction|Krakatau Aqua Coaster', 'vb', 'vb-krakatau', 'attraction', 'attraction', 'coaster', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Water coaster', 'Krakatau Aqua Coaster', '{"he": "קראקטאו אקווה קוסטר"}'::jsonb, '{"he": ["קראקטאו"]}'::jsonb, 4, 2017, null, 107, null, 'may_get_soaked', 'outdoor', 'na', 'transfer_to_ride_vehicle', 'false', 'na', 'na', 'true', 'true', null, 'false', 'false', 'true', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-meet-vol-the-spirit-of-krakatau', 'Universal Volcano Bay|Entertainment|Meet Vol: the Spirit of Krakatau', 'vb', 'vb-krakatau', 'entertainment', 'meet_greet', 'meet_greet', 'open', null, 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate reservation normally required; check showtimes in Universal app.', 'Yes', 'Character show', 'Meet Vol: the Spirit of Krakatau', '{"he": "מיט וול: דה ספיריט אוף קראקטאו"}'::jsonb, '{"he": []}'::jsonb, 1, 2017, null, 0, null, 'na', 'mixed', 'na', 'remain_in_wheelchair', 'false', 'na', 'false', 'na', 'na', null, 'false', 'na', 'false', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-kala-and-tai-nui-serpentine-body-slides', 'Universal Volcano Bay|Attraction|Kala and Tai Nui Serpentine Body Slides', 'vb', 'vb-rainforest-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Body slide', 'Kala and Tai Nui Serpentine Body Slides', '{"he": "קאלה וטאי נוי סרפנטיין בודי סליידס"}'::jsonb, '{"he": []}'::jsonb, 4, 2017, null, 122, null, 'may_get_soaked', 'outdoor', 'na', 'must_be_ambulatory', 'false', 'na', 'na', 'true', 'true', null, 'true', 'true', 'true', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-maku-of-maku-puihi-round-raft-rides', 'Universal Volcano Bay|Attraction|Maku of Maku Puihi Round Raft Rides', 'vb', 'vb-rainforest-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'River rapids', 'Maku of Maku Puihi Round Raft Rides', '{"he": "מאקו אוף מאקו פויהי ראונד ראפט ריידס"}'::jsonb, '{"he": []}'::jsonb, 3, 2017, null, 107, null, 'may_get_soaked', 'outdoor', 'na', 'transfer_to_ride_vehicle', 'true', 'na', 'na', 'true', 'true', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-ohno-of-ohyah-and-ohno-drop-slides', 'Universal Volcano Bay|Attraction|Ohno of Ohyah and Ohno Drop Slides', 'vb', 'vb-rainforest-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Body slide', 'Ohno of Ohyah and Ohno Drop Slides', '{"he": "אוהנו אוף אוהיה אנד אוהנו דרופ סליידס"}'::jsonb, '{"he": []}'::jsonb, 4, 2017, null, 122, null, 'may_get_soaked', 'outdoor', 'na', 'must_be_ambulatory', 'false', 'na', 'na', 'true', 'false', null, 'false', 'true', 'true', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-ohyah-of-ohyah-and-ohno-drop-slides', 'Universal Volcano Bay|Attraction|Ohyah of Ohyah and Ohno Drop Slides', 'vb', 'vb-rainforest-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Body slide', 'Ohyah of Ohyah and Ohno Drop Slides', '{"he": "אוהיה אוף אוהיה אנד אוהנו דרופ סליידס"}'::jsonb, '{"he": []}'::jsonb, 4, 2017, null, 122, null, 'may_get_soaked', 'outdoor', 'na', 'must_be_ambulatory', 'false', 'na', 'na', 'true', 'false', null, 'false', 'true', 'true', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-puihi-of-maku-puihi-round-raft-rides', 'Universal Volcano Bay|Attraction|Puihi of Maku Puihi Round Raft Rides', 'vb', 'vb-rainforest-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'River rapids', 'Puihi of Maku Puihi Round Raft Rides', '{"he": "פויהי אוף מאקו פויהי ראונד ראפט ריידס"}'::jsonb, '{"he": []}'::jsonb, 4, 2017, null, 107, null, 'may_get_soaked', 'outdoor', 'na', 'transfer_to_ride_vehicle', 'true', 'na', 'na', 'true', 'true', null, 'true', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-puka-uli-lagoon', 'Universal Volcano Bay|Attraction|Puka Uli Lagoon', 'vb', 'vb-rainforest-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Wave pool', 'Puka Uli Lagoon', '{"he": "פוקה אולי לגון"}'::jsonb, '{"he": []}'::jsonb, 1, 2017, null, 0, null, 'may_get_soaked', 'outdoor', 'na', 'remain_in_wheelchair', 'false', 'na', 'na', 'na', 'na', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-punga-racers', 'Universal Volcano Bay|Attraction|Punga Racers', 'vb', 'vb-rainforest-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Mat racing slide', 'Punga Racers', '{"he": "פונגה רייסרס"}'::jsonb, '{"he": []}'::jsonb, 3, 2017, null, 107, null, 'may_get_soaked', 'outdoor', 'na', 'must_be_ambulatory', 'false', 'na', 'na', 'true', 'false', null, 'true', 'false', 'true', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-raki-of-taniwha-tubes', 'Universal Volcano Bay|Attraction|Raki of Taniwha Tubes', 'vb', 'vb-rainforest-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Tube / raft slide', 'Raki of Taniwha Tubes', '{"he": "טאניווה טיובס"}'::jsonb, '{"he": []}'::jsonb, 3, 2017, null, 107, null, 'may_get_soaked', 'outdoor', 'na', 'transfer_to_ride_vehicle', 'true', 'na', 'na', 'true', 'true', null, 'true', 'false', 'true', 'false', null, null, '2026-09-07'),
('universal-volcano-bay-teawa-the-fearless-river', 'Universal Volcano Bay|Attraction|TeAwa The Fearless River', 'vb', 'vb-rainforest-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'River rapids', 'TeAwa The Fearless River', '{"he": "טה אווה דה פירלס ריבר"}'::jsonb, '{"he": []}'::jsonb, 3, 2017, null, 107, null, 'may_get_soaked', 'outdoor', 'na', 'transfer_to_ride_vehicle', 'false', 'na', 'na', 'false', 'false', null, 'false', 'false', 'true', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-tonga-of-taniwha-tubes', 'Universal Volcano Bay|Attraction|Tonga of Taniwha Tubes', 'vb', 'vb-rainforest-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Tube / raft slide', 'Tonga of Taniwha Tubes', '{"he": "טאניווה טיובס"}'::jsonb, '{"he": []}'::jsonb, 3, 2017, null, 107, null, 'may_get_soaked', 'outdoor', 'na', 'transfer_to_ride_vehicle', 'true', 'na', 'na', 'true', 'true', null, 'false', 'false', 'true', 'false', null, null, '2026-09-07'),
('universal-volcano-bay-kopiko-wai-winding-river', 'Universal Volcano Bay|Attraction|Kopiko Wai Winding River', 'vb', 'vb-river-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Lazy river', 'Kopiko Wai Winding River', '{"he": "קופיקו וואי וויינדינג ריבר"}'::jsonb, '{"he": []}'::jsonb, 1, 2017, null, 0, null, 'may_get_soaked', 'outdoor', 'na', 'transfer_to_ride_vehicle', 'false', 'na', 'na', 'false', 'false', null, 'true', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-runamukka-reef', 'Universal Volcano Bay|Attraction|Runamukka Reef', 'vb', 'vb-river-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Water play area', 'Runamukka Reef', '{"he": "רונאמוקה ריף"}'::jsonb, '{"he": []}'::jsonb, 1, 2017, null, null, 137, 'may_get_soaked', 'outdoor', 'na', 'remain_in_wheelchair', 'false', 'na', 'na', 'na', 'na', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-tot-tiki-reef', 'Universal Volcano Bay|Attraction|Tot Tiki Reef', 'vb', 'vb-river-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Water play area', 'Tot Tiki Reef', '{"he": "טוט טיקי ריף"}'::jsonb, '{"he": []}'::jsonb, 1, 2017, null, null, 122, 'may_get_soaked', 'outdoor', 'na', 'remain_in_wheelchair', 'false', 'na', 'na', 'na', 'na', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-honu-of-honu-ika-moana', 'Universal Volcano Bay|Attraction|Honu of Honu ika Moana', 'vb', 'vb-wave-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Tube / raft slide', 'Honu of Honu ika Moana', '{"he": "הונו אוף הונו איקה מואנה"}'::jsonb, '{"he": []}'::jsonb, 4, 2017, null, 122, null, 'may_get_soaked', 'outdoor', 'na', 'transfer_to_ride_vehicle', 'true', 'na', 'na', 'true', 'true', null, 'false', 'true', 'false', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-ika-moana-of-honu-ika-moana', 'Universal Volcano Bay|Attraction|ika Moana of Honu ika Moana', 'vb', 'vb-wave-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Tube / raft slide', 'ika Moana of Honu ika Moana', '{"he": "איקה מואנה אוף הונו איקה מואנה"}'::jsonb, '{"he": []}'::jsonb, 3, 2017, null, 107, null, 'may_get_soaked', 'outdoor', 'na', 'transfer_to_ride_vehicle', 'true', 'na', 'na', 'true', 'true', null, 'false', 'true', 'false', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-the-reef', 'Universal Volcano Bay|Attraction|The Reef', 'vb', 'vb-wave-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Wave pool', 'The Reef', '{"he": "דה ריף"}'::jsonb, '{"he": []}'::jsonb, 1, 2017, null, 0, null, 'may_get_soaked', 'outdoor', 'na', 'remain_in_wheelchair', 'false', 'na', 'na', 'na', 'na', null, 'false', 'false', 'false', 'false', null, null, '2026-08-24'),
('universal-volcano-bay-waturi-beach', 'Universal Volcano Bay|Attraction|Waturi Beach', 'vb', 'vb-wave-village', 'attraction', 'attraction', 'water_ride', 'open', 'Open as of Aug 24, 2026. Planned park maintenance closure begins Oct 26, 2026.', 'Valid admission to Universal Volcano Bay or an eligible multi-park/pass product that includes Volcano Bay.', 'No separate ride reservation normally required; use standby/approved access options. Check Universal app for day-of changes.', 'Yes', 'Wave pool', 'Waturi Beach', '{"he": "וואטורי ביץ''"}'::jsonb, '{"he": []}'::jsonb, 2, 2017, null, 0, null, 'may_get_soaked', 'outdoor', 'na', 'remain_in_wheelchair', 'false', 'na', 'na', 'true', 'false', null, 'false', 'false', 'true', 'false', null, null, '2026-08-24')
on conflict (id) do update set
  key = excluded.key,
  park_id = excluded.park_id,
  land_id = excluded.land_id,
  kind = excluded.kind,
  type = excluded.type,
  category = excluded.category,
  status = excluded.status,
  status_note = excluded.status_note,
  admission = excluded.admission,
  reservation = excluded.reservation,
  included_with_admission = excluded.included_with_admission,
  subtype = excluded.subtype,
  name = excluded.name,
  name_i18n = excluded.name_i18n,
  aliases_i18n = excluded.aliases_i18n,
  intensity = excluded.intensity,
  opened_year = excluded.opened_year,
  duration_minutes = excluded.duration_minutes,
  height_requirement_cm = excluded.height_requirement_cm,
  max_height_requirement_cm = excluded.max_height_requirement_cm,
  gets_wet = excluded.gets_wet,
  environment = excluded.environment,
  air_conditioned = excluded.air_conditioned,
  wheelchair = excluded.wheelchair,
  motion_sickness_warning = excluded.motion_sickness_warning,
  is_motion_simulator = excluded.is_motion_simulator,
  uses_large_screens_or_3d = excluded.uses_large_screens_or_3d,
  big_drops = excluded.big_drops,
  spinning = excluded.spinning,
  skip_line_system = excluded.skip_line_system,
  sens_enclosed_dark = excluded.sens_enclosed_dark,
  sens_heights = excluded.sens_heights,
  sens_loud_sudden = excluded.sens_loud_sudden,
  sens_strobe = excluded.sens_strobe,
  max_speed_kmh = excluded.max_speed_kmh,
  inversions = excluded.inversions,
  last_verified = excluded.last_verified,
  updated_at = now();

COMMIT;

-- ── אימות התוכן ──────────────────────────────────────────────────────
-- ספירה לבדה תגיד "232 שורות" גם אם שלושת המצבים נמעכו. הבדיקה הזו
-- משווה שני מספרים לכל שדה:
--   במסד   — מה שיש עכשיו בסופאבייס
--   בייצוא — מה שיש בקובץ שממנו נוצר ה-SQL הזה
--
-- ⚠️ **שתי עמודות ולא שלוש.** הייתה כאן עמודה שלישית, "אצלך", שהשוותה
-- למספרים שנמסרו על המאסטר. היא הפסיקה להיות נחוצה כשהייצוא נבנה
-- מהמאסטר עצמו, והמספרים שבה נשארו קפואים — כלומר היא הדליקה ⚠️ על
-- טעינה תקינה בכל מנת תוכן חדשה.
--
-- במסד ≠ בייצוא → ❌ משהו נמעך במעבר. זו ההשוואה שמגלה תקלה.
--
-- אפשר להריץ אותה שוב בכל רגע, לבד.

with checks as (
  select 1 as ord,
         'שורות ב-experience' as "בדיקה",
         (select count(*) from experience)::text as "במסד",
         '242' as "בייצוא",
         case when (select count(*) from experience) <> 242 then '❌ נמעך במעבר — במסד יש משהו אחר ממה שיצא'
              else '✅ תקין' end as "מצב"

  union all
  select 2 as ord,
         'height > 0 (יש מגבלה)' as "בדיקה",
         (select count(*) from experience where height_requirement_cm > 0)::text as "במסד",
         '74' as "בייצוא",
         case when (select count(*) from experience where height_requirement_cm > 0) <> 74 then '❌ נמעך במעבר — במסד יש משהו אחר ממה שיצא'
              else '✅ תקין' end as "מצב"

  union all
  select 3 as ord,
         'height = 0 (נבדק, אין מגבלה)' as "בדיקה",
         (select count(*) from experience where height_requirement_cm = 0)::text as "במסד",
         '163' as "בייצוא",
         case when (select count(*) from experience where height_requirement_cm = 0) <> 163 then '❌ נמעך במעבר — במסד יש משהו אחר ממה שיצא'
              else '✅ תקין' end as "מצב"

  union all
  select 4 as ord,
         'height NULL (לא נבדק)' as "בדיקה",
         (select count(*) from experience where height_requirement_cm is null)::text as "במסד",
         '5' as "בייצוא",
         case when (select count(*) from experience where height_requirement_cm is null) <> 5 then '❌ נמעך במעבר — במסד יש משהו אחר ממה שיצא'
              else '✅ תקין' end as "מצב"

  union all
  select 5 as ord,
         'gets_wet = ''na''' as "בדיקה",
         (select count(*) from experience where gets_wet = 'na')::text as "במסד",
         '77' as "בייצוא",
         case when (select count(*) from experience where gets_wet = 'na') <> 77 then '❌ נמעך במעבר — במסד יש משהו אחר ממה שיצא'
              else '✅ תקין — ''na'' הוא מופע, וזו תשובה' end as "מצב"

  union all
  select 6 as ord,
         'gets_wet NULL (לא נבדק)' as "בדיקה",
         (select count(*) from experience where gets_wet is null)::text as "במסד",
         '0' as "בייצוא",
         case when (select count(*) from experience where gets_wet is null) <> 0 then '❌ נמעך במעבר — במסד יש משהו אחר ממה שיצא'
              else '✅ תקין' end as "מצב"

  union all
  select 7 as ord,
         'intensity NULL' as "בדיקה",
         (select count(*) from experience where intensity is null)::text as "במסד",
         '0' as "בייצוא",
         case when (select count(*) from experience where intensity is null) <> 0 then '❌ נמעך במעבר — במסד יש משהו אחר ממה שיצא'
              else '✅ תקין' end as "מצב"

  union all
  select 8 as ord,
         'wheelchair NULL' as "בדיקה",
         (select count(*) from experience where wheelchair is null)::text as "במסד",
         '1' as "בייצוא",
         case when (select count(*) from experience where wheelchair is null) <> 1 then '❌ נמעך במעבר — במסד יש משהו אחר ממה שיצא'
              else '✅ תקין — Tike''s Peak, וזה נכון' end as "מצב"

  union all
  select 9,
         'שם עברי לכל שורה',
         (select count(*) from experience where name_i18n->>'he' is null or name_i18n->>'he' = '')::text,
         '0',
         case when (select count(*) from experience where name_i18n->>'he' is null or name_i18n->>'he' = '') = 0
                then '✅ תקין — לכל השורות יש שם עברי'
              else '❌ שורות בלי שם עברי' end

  union all
  select 10,
         'status — לא הכל open',
         (select string_agg(status || ': ' || n, ' · ' order by status)
            from (select status, count(*) as n from experience group by status) s),
         '236 open · 3 closed · 2 temporarily_closed · 1 coming_soon',
         case when (select count(*) from experience where status = 'closed') > 0
                then '✅ תקין — הסגורים נשמרו כסגורים'
              else '❌ הכל נטען כ-open. מתקן סגור שמוצג כפתוח הוא באג' end

  union all
  select 11,
         'פארקים מיוצגים',
         (select count(distinct park_id) from experience)::text,
         '10',
         case when (select count(distinct park_id) from experience) = 10
                then '✅ תקין' else '❌ פארק חסר' end

  union all
  select 11.5,
         'מוצר דילוג בתור',
         (select string_agg(coalesce(skip_line_system,'(לא נבדק)') || ': ' || n, ' · ' order by n desc)
            from (select skip_line_system, count(*) as n from experience group by 1) s),
         'none: 83 · (לא נבדק): 76 · multi_pass: 51 · express: 27 · single_pass: 5',
         case when (select count(*) from experience where skip_line_system is null) = 76
               and (select count(*) from experience where skip_line_system = 'none') = 83
                then '✅ תקין — NULL הוא "לא נבדק", לא "אין"'
              else '❌ לא תואם לייצוא' end

  union all
  select 12,
         'שורות שנעצרו בכוונה',
         '0',
         '0',
         '✅ תקין — שום שורה לא נעצרה'

)
select "בדיקה", "במסד", "בייצוא", "מצב" from checks order by ord;
