-- Park Day Companion — מה שכבר אינו בייצוא
--
-- ⚠️ **מוחק שורות.** להריץ **אחרי** קובצי התוכן, ורק אחריהם.
--
-- הטעינה היא upsert ואינה מוחקת דבר. שורה שהוסרה מהמאסטר — כי הוחלפה,
-- כי הוחלט להדיר אותה, או כי נשמטה בטעות — נשארת במסד וטים ממשיך לענות
-- עליה. זה בדיוק "תוכן ישן שמוצג כאילו הוא עדכני".
--
-- הרשימה נגזרת מהייצוא הנוכחי (242 שורות), ולכן היא תמיד
-- מעודכנת. אין כאן מפתחות כתובים ביד.

BEGIN;

create temporary table _current (key text primary key) on commit drop;
insert into _current (key) values
  ('Disney''s Animal Kingdom|Entertainment|Festival of the Lion King'),
  ('Disney''s Animal Kingdom|Attraction|Gorilla Falls Exploration Trail'),
  ('Disney''s Animal Kingdom|Entertainment|Harambe Village Street Band – Burudika'),
  ('Disney''s Animal Kingdom|Attraction|Kilimanjaro Safaris'),
  ('Disney''s Animal Kingdom|Entertainment|Tam Tam Drummers of Harambe'),
  ('Disney''s Animal Kingdom|Attraction|Wildlife Express Train'),
  ('Disney''s Animal Kingdom|Attraction|Expedition Everest – Legend of the Forbidden Mountain'),
  ('Disney''s Animal Kingdom|Entertainment|Feathered Friends in Flight!'),
  ('Disney''s Animal Kingdom|Attraction|Kali River Rapids'),
  ('Disney''s Animal Kingdom|Attraction|Maharajah Jungle Trek'),
  ('Disney''s Animal Kingdom|Attraction|Discovery Island Trails'),
  ('Disney''s Animal Kingdom|Attraction|Tree of Life'),
  ('Disney''s Animal Kingdom|Entertainment|Tree of Life Awakenings'),
  ('Disney''s Animal Kingdom|Entertainment|Viva Gaia Street Band!'),
  ('Disney''s Animal Kingdom|Entertainment|Winged Encounters – The Kingdom Takes Flight'),
  ('Disney''s Animal Kingdom|Entertainment|Adventures with Kevin on Discovery Island'),
  ('Disney''s Animal Kingdom|Entertainment|Meet Favorite Disney Pals at Adventurers Outpost'),
  ('Disney''s Animal Kingdom|Entertainment|Meet Moana at Character Landing'),
  ('Disney''s Animal Kingdom|Entertainment|Zoogether Day Gathering Spot'),
  ('Disney''s Animal Kingdom|Attraction|The Oasis Exhibits'),
  ('Disney''s Animal Kingdom|Attraction|Avatar Flight of Passage'),
  ('Disney''s Animal Kingdom|Attraction|Na''vi River Journey'),
  ('Disney''s Animal Kingdom|Attraction|Wilderness Explorers'),
  ('Disney''s Animal Kingdom|Attraction|Animal Care at Conservation Station'),
  ('Disney''s Animal Kingdom|Attraction|Bluey''s Wild World at Conservation Station'),
  ('Disney''s Animal Kingdom|Entertainment|Jumping Junction'),
  ('Disney''s Animal Kingdom|Entertainment|Finding Nemo: The Big Blue... and Beyond!'),
  ('Disney''s Animal Kingdom|Entertainment|Zootopia: Better Zoogether!'),
  ('Disney''s Blizzard Beach|Attraction|Melt-Away Bay'),
  ('Disney''s Blizzard Beach|Attraction|Chairlift'),
  ('Disney''s Blizzard Beach|Attraction|Downhill Double Dipper'),
  ('Disney''s Blizzard Beach|Attraction|Runoff Rapids'),
  ('Disney''s Blizzard Beach|Attraction|Slush Gusher'),
  ('Disney''s Blizzard Beach|Attraction|Snow Stormers'),
  ('Disney''s Blizzard Beach|Attraction|Summit Plummet'),
  ('Disney''s Blizzard Beach|Attraction|Teamboat Springs'),
  ('Disney''s Blizzard Beach|Attraction|Toboggan Racers'),
  ('Disney''s Blizzard Beach|Attraction|Cross Country Creek'),
  ('Disney''s Blizzard Beach|Attraction|Ski Patrol Training Camp'),
  ('Disney''s Blizzard Beach|Attraction|Tike''s Peak'),
  ('Disney''s Hollywood Studios|Entertainment|Disney Jr. Mickey Mouse Clubhouse Live!'),
  ('Disney''s Hollywood Studios|Entertainment|The Little Mermaid – A Musical Adventure'),
  ('Disney''s Hollywood Studios|Attraction|The Magic of Disney Animation'),
  ('Disney''s Hollywood Studios|Attraction|Vacation Fun'),
  ('Disney''s Hollywood Studios|Attraction|Walt Disney Presents'),
  ('Disney''s Hollywood Studios|Entertainment|Disney Movie Magic'),
  ('Disney''s Hollywood Studios|Entertainment|Wonderful World of Animation'),
  ('Disney''s Hollywood Studios|Entertainment|For the First Time in Forever: A Frozen Sing-Along Celebration'),
  ('Disney''s Hollywood Studios|Entertainment|Indiana Jones Epic Stunt Spectacular!'),
  ('Disney''s Hollywood Studios|Attraction|Star Tours – The Adventures Continue'),
  ('Disney''s Hollywood Studios|Attraction|Mickey & Minnie''s Runaway Railway'),
  ('Disney''s Hollywood Studios|Entertainment|Green Army Drum Corps'),
  ('Disney''s Hollywood Studios|Entertainment|Hollygroove Swingin'''),
  ('Disney''s Hollywood Studios|Entertainment|The Record Setters'),
  ('Disney''s Hollywood Studios|Attraction|Millennium Falcon: Smugglers Run'),
  ('Disney''s Hollywood Studios|Attraction|Star Wars: Rise of the Resistance'),
  ('Disney''s Hollywood Studios|Entertainment|Beauty and the Beast – Live on Stage'),
  ('Disney''s Hollywood Studios|Entertainment|Disney Villains: Unfairly Ever After'),
  ('Disney''s Hollywood Studios|Entertainment|Fantasmic!'),
  ('Disney''s Hollywood Studios|Attraction|Rock ''n'' Roller Coaster Starring The Muppets'),
  ('Disney''s Hollywood Studios|Attraction|The Twilight Zone Tower of Terror'),
  ('Disney''s Hollywood Studios|Attraction|Alien Swirling Saucers'),
  ('Disney''s Hollywood Studios|Attraction|Slinky Dog Dash'),
  ('Disney''s Hollywood Studios|Attraction|Toy Story Mania!'),
  ('Disney''s Typhoon Lagoon|Attraction|Crush ''n'' Gusher'),
  ('Disney''s Typhoon Lagoon|Attraction|Ketchakiddee Creek'),
  ('Disney''s Typhoon Lagoon|Attraction|Gangplank Falls'),
  ('Disney''s Typhoon Lagoon|Attraction|Humunga Kowabunga'),
  ('Disney''s Typhoon Lagoon|Attraction|Keelhaul Falls'),
  ('Disney''s Typhoon Lagoon|Attraction|Mayday Falls'),
  ('Disney''s Typhoon Lagoon|Attraction|Miss Adventure Falls'),
  ('Disney''s Typhoon Lagoon|Attraction|Storm Slides'),
  ('Disney''s Typhoon Lagoon|Attraction|Castaway Creek'),
  ('Disney''s Typhoon Lagoon|Attraction|Typhoon Lagoon Surf Pool'),
  ('Disney''s Typhoon Lagoon|Attraction|Bay Slides'),
  ('EPCOT|Entertainment|JAMMitors'),
  ('EPCOT|Entertainment|Disney and Pixar Short Film Festival'),
  ('EPCOT|Attraction|Journey Into Imagination With Figment'),
  ('EPCOT|Attraction|Spaceship Earth'),
  ('EPCOT|Attraction|Advanced Training Lab'),
  ('EPCOT|Attraction|Guardians of the Galaxy: Cosmic Rewind'),
  ('EPCOT|Attraction|Mission: SPACE – Green'),
  ('EPCOT|Attraction|Mission: SPACE – Orange'),
  ('EPCOT|Attraction|Test Track'),
  ('EPCOT|Entertainment|Awesome Planet'),
  ('EPCOT|Attraction|Bruce''s Shark World'),
  ('EPCOT|Attraction|Journey of Water, Inspired by Moana'),
  ('EPCOT|Attraction|Living with the Land'),
  ('EPCOT|Attraction|Soarin'' Across America'),
  ('EPCOT|Attraction|The Seas with Nemo & Friends'),
  ('EPCOT|Entertainment|Turtle Talk With Crush'),
  ('EPCOT|Entertainment|The American Adventure'),
  ('EPCOT|Entertainment|Voices of Liberty'),
  ('EPCOT|Entertainment|Canada Far and Wide in Circle-Vision 360'),
  ('EPCOT|Entertainment|Acrobatico!'),
  ('EPCOT|Entertainment|Beauty and the Beast Sing-Along'),
  ('EPCOT|Attraction|Remy''s Ratatouille Adventure'),
  ('EPCOT|Entertainment|Matsuriza'),
  ('EPCOT|Attraction|Gran Fiesta Tour Starring The Three Caballeros'),
  ('EPCOT|Entertainment|Mariachi Cobre'),
  ('EPCOT|Attraction|Frozen Ever After'),
  ('EPCOT|Entertainment|Command Performance'),
  ('EPCOT|Entertainment|Luminous: The Symphony of Us'),
  ('Magic Kingdom|Attraction|Jungle Cruise'),
  ('Magic Kingdom|Attraction|Pirates of the Caribbean'),
  ('Magic Kingdom|Attraction|Swiss Family Treehouse'),
  ('Magic Kingdom|Attraction|The Magic Carpets of Aladdin'),
  ('Magic Kingdom|Entertainment|Walt Disney''s Enchanted Tiki Room'),
  ('Magic Kingdom|Entertainment|Happily Ever After'),
  ('Magic Kingdom|Attraction|Enchanted Tales with Belle'),
  ('Magic Kingdom|Attraction|it''s a small world'),
  ('Magic Kingdom|Attraction|Mad Tea Party'),
  ('Magic Kingdom|Entertainment|Mickey''s PhilharMagic'),
  ('Magic Kingdom|Attraction|Peter Pan''s Flight'),
  ('Magic Kingdom|Attraction|Prince Charming Regal Carrousel'),
  ('Magic Kingdom|Attraction|Seven Dwarfs Mine Train'),
  ('Magic Kingdom|Attraction|The Many Adventures of Winnie the Pooh'),
  ('Magic Kingdom|Attraction|Under the Sea ~ Journey of The Little Mermaid'),
  ('Magic Kingdom|Attraction|Casey Jr. Splash ''N'' Soak Station'),
  ('Magic Kingdom|Attraction|Dumbo the Flying Elephant'),
  ('Magic Kingdom|Attraction|The Barnstormer'),
  ('Magic Kingdom|Attraction|Big Thunder Mountain Railroad'),
  ('Magic Kingdom|Entertainment|Country Bear Musical Jamboree'),
  ('Magic Kingdom|Attraction|Tiana''s Bayou Adventure'),
  ('Magic Kingdom|Attraction|Haunted Mansion'),
  ('Magic Kingdom|Entertainment|The Hall of Presidents'),
  ('Magic Kingdom|Entertainment|Casey''s Corner Pianist'),
  ('Magic Kingdom|Entertainment|The Dapper Dans'),
  ('Magic Kingdom|Entertainment|Disney Adventure Friends Cavalcade'),
  ('Magic Kingdom|Entertainment|Disney Festival of Fantasy Parade'),
  ('Magic Kingdom|Entertainment|Disney Starlight: Dream the Night Away'),
  ('Magic Kingdom|Attraction|Astro Orbiter'),
  ('Magic Kingdom|Attraction|Buzz Lightyear''s Space Ranger Spin'),
  ('Magic Kingdom|Entertainment|Monsters Inc. Laugh Floor'),
  ('Magic Kingdom|Attraction|Space Mountain'),
  ('Magic Kingdom|Attraction|Tomorrowland Speedway'),
  ('Magic Kingdom|Attraction|Tomorrowland Transit Authority PeopleMover'),
  ('Magic Kingdom|Attraction|TRON Lightcycle / Run'),
  ('Magic Kingdom|Attraction|Walt Disney''s Carousel of Progress'),
  ('Universal Epic Universe|Attraction|Astronomica'),
  ('Universal Epic Universe|Attraction|Constellation Carousel'),
  ('Universal Epic Universe|Attraction|Stardust Racers'),
  ('Universal Epic Universe|Attraction|Curse of the Werewolf'),
  ('Universal Epic Universe|Entertainment|Dark Universe Character Meet & Greet'),
  ('Universal Epic Universe|Attraction|Darkmoor Monster Makeup Experience'),
  ('Universal Epic Universe|Attraction|Monsters Unchained: The Frankenstein Experiment'),
  ('Universal Epic Universe|Attraction|Dragon Racer''s Rally'),
  ('Universal Epic Universe|Attraction|Fyre Drill'),
  ('Universal Epic Universe|Attraction|Hiccup''s Wing Gliders'),
  ('Universal Epic Universe|Entertainment|Meet Toothless and Friends'),
  ('Universal Epic Universe|Entertainment|The Untrainable Dragon'),
  ('Universal Epic Universe|Attraction|Viking Training Camp'),
  ('Universal Epic Universe|Attraction|Mario Kart: Bowser''s Challenge'),
  ('Universal Epic Universe|Entertainment|Meet Mario, Luigi, Princess Peach and Toad'),
  ('Universal Epic Universe|Attraction|Yoshi''s Adventure'),
  ('Universal Epic Universe|Entertainment|Meet Donkey Kong'),
  ('Universal Epic Universe|Attraction|Mine-Cart Madness'),
  ('Universal Epic Universe|Attraction|Harry Potter and the Battle at the Ministry'),
  ('Universal Epic Universe|Entertainment|Le Cirque Arcanus'),
  ('Universal Islands of Adventure|Entertainment|Frog Choir'),
  ('Universal Islands of Adventure|Attraction|Ollivanders – Hogsmeade'),
  ('Universal Islands of Adventure|Entertainment|Triwizard Spirit Rally'),
  ('Universal Islands of Adventure|Attraction|Camp Jurassic'),
  ('Universal Islands of Adventure|Attraction|Jurassic Park Discovery Center'),
  ('Universal Islands of Adventure|Attraction|Jurassic Park River Adventure'),
  ('Universal Islands of Adventure|Attraction|Jurassic World VelociCoaster'),
  ('Universal Islands of Adventure|Attraction|Pteranodon Flyers'),
  ('Universal Islands of Adventure|Attraction|Raptor Encounter'),
  ('Universal Islands of Adventure|Attraction|Doctor Doom''s Fearfall'),
  ('Universal Islands of Adventure|Entertainment|Meet the Marvel Super Heroes'),
  ('Universal Islands of Adventure|Attraction|Storm Force Accelatron'),
  ('Universal Islands of Adventure|Attraction|The Amazing Adventures of Spider-Man'),
  ('Universal Islands of Adventure|Attraction|The Incredible Hulk Coaster'),
  ('Universal Islands of Adventure|Attraction|Caro-Seuss-el'),
  ('Universal Islands of Adventure|Entertainment|Dr. Seuss Character Zone'),
  ('Universal Islands of Adventure|Attraction|If I Ran The Zoo'),
  ('Universal Islands of Adventure|Entertainment|Oh! The Stories You''ll Hear!'),
  ('Universal Islands of Adventure|Attraction|One Fish, Two Fish, Red Fish, Blue Fish'),
  ('Universal Islands of Adventure|Attraction|The Cat in the Hat'),
  ('Universal Islands of Adventure|Attraction|The High in the Sky Seuss Trolley Train Ride!'),
  ('Universal Islands of Adventure|Attraction|Skull Island: Reign of Kong'),
  ('Universal Islands of Adventure|Attraction|Flight of the Hippogriff'),
  ('Universal Islands of Adventure|Attraction|Hagrid''s Magical Creatures Motorbike Adventure'),
  ('Universal Islands of Adventure|Attraction|Harry Potter and the Forbidden Journey'),
  ('Universal Islands of Adventure|Attraction|Hogwarts Express – Hogsmeade Station'),
  ('Universal Islands of Adventure|Entertainment|Classic Comic Strip Characters'),
  ('Universal Islands of Adventure|Attraction|Dudley Do-Right''s Ripsaw Falls'),
  ('Universal Islands of Adventure|Attraction|Me Ship, The Olive'),
  ('Universal Islands of Adventure|Attraction|Popeye & Bluto''s Bilge-Rat Barges'),
  ('Universal Studios Florida|Entertainment|Celestina Warbeck and the Banshees'),
  ('Universal Studios Florida|Attraction|Ollivanders – Diagon Alley'),
  ('Universal Studios Florida|Entertainment|The Tales of Beedle the Bard'),
  ('Universal Studios Florida|Entertainment|DreamWorks Imagination Celebration'),
  ('Universal Studios Florida|Attraction|King Harold''s Swamp Symphony'),
  ('Universal Studios Florida|Attraction|Mama Luna Feline Fiesta'),
  ('Universal Studios Florida|Entertainment|Po Live!'),
  ('Universal Studios Florida|Attraction|Po''s Kung Fu Training Camp'),
  ('Universal Studios Florida|Attraction|Poppy''s Playground'),
  ('Universal Studios Florida|Attraction|Shrek''s Swamp for Little Ogres'),
  ('Universal Studios Florida|Attraction|Trolls Trollercoaster'),
  ('Universal Studios Florida|Entertainment|Animal Actors On Location!'),
  ('Universal Studios Florida|Attraction|E.T. Adventure'),
  ('Universal Studios Florida|Entertainment|Marilyn and the Diamond Bellas'),
  ('Universal Studios Florida|Entertainment|The Bourne Stuntacular'),
  ('Universal Studios Florida|Entertainment|Universal Orlando''s Horror Make-Up Show'),
  ('Universal Studios Florida|Attraction|Despicable Me Minion Mayhem'),
  ('Universal Studios Florida|Entertainment|Illumination Theater'),
  ('Universal Studios Florida|Attraction|Illumination''s Villain-Con Minion Blast'),
  ('Universal Studios Florida|Entertainment|¡Vamos! – Báilalo'),
  ('Universal Studios Florida|Attraction|Race Through New York Starring Jimmy Fallon'),
  ('Universal Studios Florida|Attraction|Revenge of the Mummy'),
  ('Universal Studios Florida|Entertainment|The Blues Brothers Show'),
  ('Universal Studios Florida|Attraction|TRANSFORMERS: The Ride-3D'),
  ('Universal Studios Florida|Entertainment|Universal Mega Movie Parade'),
  ('Universal Studios Florida|Entertainment|Beat Builders'),
  ('Universal Studios Florida|Attraction|Fast & Furious – Supercharged'),
  ('Universal Studios Florida|Attraction|Kang & Kodos'' Twirl ''n'' Hurl'),
  ('Universal Studios Florida|Attraction|The Simpsons Ride'),
  ('Universal Studios Florida|Attraction|Harry Potter and the Escape from Gringotts'),
  ('Universal Studios Florida|Attraction|Hogwarts Express – King''s Cross Station'),
  ('Universal Studios Florida|Entertainment|CineSational: A Symphonic Spectacular'),
  ('Universal Studios Florida|Attraction|MEN IN BLACK Alien Attack'),
  ('Universal Volcano Bay|Attraction|Ko''okiri Body Plunge'),
  ('Universal Volcano Bay|Attraction|Krakatau Aqua Coaster'),
  ('Universal Volcano Bay|Entertainment|Meet Vol: the Spirit of Krakatau'),
  ('Universal Volcano Bay|Attraction|Kala and Tai Nui Serpentine Body Slides'),
  ('Universal Volcano Bay|Attraction|Maku of Maku Puihi Round Raft Rides'),
  ('Universal Volcano Bay|Attraction|Ohno of Ohyah and Ohno Drop Slides'),
  ('Universal Volcano Bay|Attraction|Ohyah of Ohyah and Ohno Drop Slides'),
  ('Universal Volcano Bay|Attraction|Puihi of Maku Puihi Round Raft Rides'),
  ('Universal Volcano Bay|Attraction|Puka Uli Lagoon'),
  ('Universal Volcano Bay|Attraction|Punga Racers'),
  ('Universal Volcano Bay|Attraction|Raki of Taniwha Tubes'),
  ('Universal Volcano Bay|Attraction|TeAwa The Fearless River'),
  ('Universal Volcano Bay|Attraction|Tonga of Taniwha Tubes'),
  ('Universal Volcano Bay|Attraction|Kopiko Wai Winding River'),
  ('Universal Volcano Bay|Attraction|Runamukka Reef'),
  ('Universal Volcano Bay|Attraction|Tot Tiki Reef'),
  ('Universal Volcano Bay|Attraction|Honu of Honu ika Moana'),
  ('Universal Volcano Bay|Attraction|ika Moana of Honu ika Moana'),
  ('Universal Volcano Bay|Attraction|The Reef'),
  ('Universal Volcano Bay|Attraction|Waturi Beach');

-- ⚠️ קודם רואים, ואז מוחקים.
select e.key as "יימחק — אינו בייצוא", e.name as "שם"
from experience e
where e.key not in (select key from _current)
order by e.key;

delete from experience e where e.key not in (select key from _current);

select count(*) as "נשארו במסד" from experience;

COMMIT;
