/**
 * ⚠️ **The caution rule lives here, not in the body of the documents** (CLAUDE.md,
 * and section 8 of the retrieval doc). A caveat paragraph inside every document
 * would pull all the documents toward each other in embedding space — the more
 * general the question, the more weight the shared paragraph carries — and would
 * also duplicate what volatility already says.
 *
 * So the rule is written once, and triggered by the volatility that comes with
 * every passage.
 */
/**
 * 🔴 **The same product logic living in two places, and that's a second source of
 * truth.**
 *
 * "מתאים / לא ידוע אם מתאים / חסר לנו הגובה" ("fits / unknown whether it fits /
 * we're missing the height") was written once in `he.json` for the results
 * screen, and once here in Tim's instructions. Paula pointed to the precedent in
 * `he.json`, and I copied it here by hand — i.e. I created exactly the
 * duplication this project forbids itself elsewhere (`skip_line_extra_cost`).
 *
 * ⚠️ **This block is generated, not written.** `scripts/build-tim-prompt.py`
 * builds it from `apps/web/src/i18n/he.json`, and a test fails if it's out of
 * date. A manual edit here will be wiped by the next build — and that's the
 * intent.
 *
 * ⚠️ **And `FIT_STAMP` is how you see it actually happened.** The function is
 * pasted by hand into Supabase, so a build-time check verifies the repo, not
 * what is live. The stamp comes back from `diagnose`, and can be compared to
 * what's in the repo.
 *
 * ── Generated automatically · do not edit by hand ──────────────────────
 */
/**
 * 🔴 **A stamp over the whole file — because `FIT_STAMP` isn't one.**
 *
 * `FIT_STAMP` hashes only the fit-rules text, so a code change that doesn't touch
 * the wording doesn't move it. On 25.09 it came back identical from the live
 * environment while `allowed_origins` didn't come back at all — i.e. the function
 * was old, and the stamp said "identical".
 *
 * ⚠️ **Generated by `scripts/build-deploy-stamp.py`. Do not edit by hand.**
 */
export const DEPLOY_STAMP = "c50472ba2d5f";
