import experiencesJson from "./experiences.json";
import parksJson from "./parks.json";
import type { Experience, Park } from "./schema";

/**
 * Both files are generated by scripts/build-dataset.py from the workbook.
 * Do not hand-edit them; edit the workbook and rebuild.
 */
export const experiences = experiencesJson as unknown as Experience[];
export const parks = parksJson as unknown as Park[];

export const byId = new Map(experiences.map((e) => [e.id, e]));

/** Coverage the UI has to be honest about rather than quietly filter away. */
export const coverage = {
  total: experiences.length,
  rated: experiences.filter((e) => e.intensity.rated).length,
  verifiedAt: experiences[0]?.sourceVerifiedAt ?? null,
};
